#ifndef _HAKO_PX4_RUNNER_CONFIG_HPP_
#define _HAKO_PX4_RUNNER_CONFIG_HPP_

#define HAKO_PX4_CHANNLE_ID_HIL_SENSOR              0
#define HAKO_PX4_CHANNLE_ID_HIL_STATE_QUATERNION    1
#define HAKO_PX4_CHANNLE_ID_HIL_GPS                 2
#define HAKO_PX4_CHANNLE_ID_HIL_ACTUATOR_CONTROLS   3

#define HAKO_PX4_RUNNER_MASTER_MAX_DELAY_USEC       1000 /* usec*/
#define HAKO_PX4_RUNNER_MASTER_DELTA_USEC           1000 /* usec*/

#endif /* _HAKO_PX4_RUNNER_CONFIG_HPP_ */