name: Build

on: 
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install GTest on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libgtest-dev
    
      - name: Install GTest on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install googletest
  
      - name: Build and Test on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd src
          set BASE_PATH=%cd%
          cmake -G "Visual Studio 17 2022" -A x64 -DHAKO_DRONE_OPTION_FILEPATH="cmake-options\win-cmake-options.cmake" .
          cmake --build . --config Release
          cd test
          set DRONE_CONFIG1_DIR=aircraft\\test-data\\drone-config1
          set DRONE_CONFIG2_DIR=aircraft\\test-data\\drone-config2
          echo DRONE_CONFIG1_DIR=%DRONE_CONFIG1_DIR%
          echo DRONE_CONFIG2_DIR=%DRONE_CONFIG2_DIR%          
          ctest -C Release --output-on-failure



      - name: Build and Test on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd src
          cmake -D HAKO_DRONE_OPTION_FILEPATH=`pwd`/cmake-options/linux-cmake-options.cmake .
          make
          cd test
          export DRONE_CONFIG1_DIR=aircraft/test-data/drone-config1
          export DRONE_CONFIG2_DIR=aircraft/test-data/drone-config2
          echo "DRONE_CONFIG1_DIR is $DRONE_CONFIG1_DIR"
          echo "DRONE_CONFIG2_DIR is $DRONE_CONFIG2_DIR"          
          ctest --output-on-failure

      - name: Build and Test on MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          cd src
          cmake .
          make
          cd test
          export DRONE_CONFIG1_DIR=aircraft/test-data/drone-config1
          export DRONE_CONFIG2_DIR=aircraft/test-data/drone-config2
          echo "DRONE_CONFIG1_DIR is $DRONE_CONFIG1_DIR"
          echo "DRONE_CONFIG2_DIR is $DRONE_CONFIG2_DIR"          
          ctest --output-on-failure
  
          

