name: Build

on: 
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install GTest on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libgtest-dev
    
      - name: Install GTest on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install googletest
  
      - name: Build and Test on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd refactor
          cmake -G "Visual Studio 17 2022" -A x64 -DHAKO_CLIENT_OPTION_FILEPATH="cmake-options/win-cmake-options.cmake" .
          cmake --build . --config Release
          ctest -C Release --output-on-failure



      - name: Build on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd refactor
          cmake -D HAKO_CLIENT_OPTION_FILEPATH=cmake-options/linux-cmake-options.cmake .
          make
          cd test
          ctest --output-on-failure

      - name: Build on MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          cd refactor
          cmake .
          make
          cd test
          ctest --output-on-failure
  
          

